### ISSUE TITLE
Terraform 13 support

### ISSUE THREAD

**Issue by ghost** [terraform-google-modules/terraform-google-folders#28]
Hi There

I can see in the version.tf you are now supporting terraform 13. However you haven't created a tag for this.

So i'm just wondering when a new tag will be created?

Cheers,

Brett

**Comment by brondum** [comment]
+1

**Comment by kir4h** [comment]
Little confused about this as well. Not just about Terraform 13, but the fact that the latest tag is `v2.0.2` dating from January.

I guess one can just clone the repo and source it locally, but I'm wondering if there is a reasony for not creating a tag when there have been several commits since then.

Also, I guess there was a mistake by doing a mass replace in #27, since https://github.com/terraform-google-modules/terraform-google-folders/blame/master/README.md#L23 references now version `v3.36.0` which refers to google provider rather than the module itself.

**Comment by bharathkkb** [comment]
Should be fixed by latest release https://github.com/terraform-google-modules/terraform-google-folders/releases/tag/v3.0.0
